name: flutter_neat_pdf_viewer_example
description: Demonstrates how to use the flutter_neat_pdf_viewer plugin.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_neat_pdf_viewer:
    path: ../
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sample.pdf
    - assets/sample2.pdf
