name: flutter_neat_pdf_viewer
description: A flutter plugin for handling PDF files. Works on both Android & iOS. Inspired by 
version: 0.2.0+10
homepage: https://github.com/rwbr/flutter_neat_pdf_viewer

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_picker: ^2.0.3
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.rwbr.flutter_neat_pdf_viewer
        pluginClass: FlutterNeatPdfViewer
      ios:
        pluginClass: FlutterNeatPdfViewer
