name: flutter_neat_pdf_viewer
description: A flutter plugin for handling PDF files. Works on both Android & iOS
version: 0.0.1
author: Ralf Weinbrecher <ralf.weinbrecher@gmail.com>
homepage: https://github.com/rwbr/flutter_neat_pdf_viewer

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^2.0.0
  numberpicker: ^1.3.0
  path_provider: ^1.6.24

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.rwbr.flutter_neat_pdf_viewer
        pluginClass: FlutterNeatPdfViewer
      ios:
        pluginClass: FlutterNeatPdfViewer
